### PR TITLE
WCM (WEM?) Learning Path QA

### PR DESCRIPTION
**Pull request by rbohl**
Made a QA pass through this. In general things worked well. Some images needed for the exercises are missing (for example, all three logo images for the About Us page, and I think the one for the very first web content that's created), and some of the images for display on LDN aren't displaying on github, so I think there are some path (e.g., ../../../images/my-image.png)issues. I tried to comment wherever I found something like this. There are some more comments in the markdown. More comments than actual changes to the content. Let me know if you have any questions.

### CODE REVIEW

**Comment by stephenkostas** [comment]
It seems like a major source of issues here is that we removed all of the introductory content where you do a extract a bundle, do a Liferay first start, set the site name, etc. Maybe we should at least do the Liferay setup so that it's clear what the site name is and all that? Otherwise we need to go back and make everything the default values, which includes reshooting the videos. @sez11a

**Comment by sez11a** [comment]
@stephenkostas why'd you shoot videos for content we deleted? I thought you'd just add a step in the beginning to go set the site name (i.e., without using the wizard; just go configure it).

**Comment by stephenkostas** [comment]
We didn't shoot the videos for the removed content, we just shot the videos of the existing content with the assumption of the "Lunar Resort" site. I had done a couple videos previously as test content for the now removed content, but that was several weeks ago. The question is, do we take a detour to System Administration to set up the portal name or do we rewind a little and start the course with the Setup Wizard?

**Comment by sez11a** [comment]
@stephenkostas We take the detour, because we don't want a section on installing or setting anything up. We're assuming a Liferay installed with all the defaults.

**Comment by rbohl** [comment]
It shouldn't take much adjusting. Probably only can two places, off the top
of my head.

**Comment by stephenkostas** [comment]
Merged

**Pull request closed without merging**
